before_install:
  - gem update --system 2.7.8
  - gem install bundler:1.17.3
  - rvm @global do gem uninstall did_you_mean
bundler_args: --without development
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script: bundle exec thor spec
cache: bundler
